package codigo;



import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ruben
 */
public class VentanaPaint1 extends javax.swing.JFrame {
    
    
   ImageIcon iconoTriangulo = new ImageIcon("/Imagenes/triangulo.png");
   ImageIcon iconoCirculo = new ImageIcon("/Imagenes/circulo.png");
     ImageIcon iconoHexagono = new ImageIcon("/Imagenes/hexagono.png");
     ImageIcon iconoEstrella = new ImageIcon("/Imagenes/estrella.png");
     ImageIcon iconoCuadrado = new ImageIcon("/Imagenes/Cuadrado.png");
   
    BufferedImage buffer,buffer2 = null;
 
    
    Color colorSeleccionado = Color.BLUE;
    
    int formaSeleccionada = 0;
    
    //creo un objeto de un circulo
    Circulo miCirculo;
    Cuadrado miCuadrado;
    Triangulo miTriangulo;
    Pentagono miPentagono;
    Hexagono miHexagono;
    
    //segunda forma de hacerlo
    Forma miforma;
    int numLados = 0;
    
    Graphics2D bufferGraphics,buffer2Graphics,lienzographics = null;
    
    //defino el icono
    ImageIcon icono;
    
    public VentanaPaint1() {
        initComponents();
        inicializarBuffers();
        EligeColor.setSize(630, 480);
        Guardar.setSize(750, 400);
            
           
    }
    
    private void imprimirDocumento(){
        
    }
    
    
    private void inicializarBuffers(){
        lienzographics = (Graphics2D) lienzo.getGraphics();
        //creo una imagen del mismo ancho y alto que el 
        //lienzo
        //hacemos un casteo
        buffer = (BufferedImage) lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
         bufferGraphics = buffer.createGraphics();
        //dibujamos rectangulo blanco de tamaño del lienzo
        bufferGraphics.setColor(Color.WHITE);
        bufferGraphics.fillRect(0, 0, buffer.getWidth(), buffer.getHeight());
        
        
        
        
        
        //inicializo el segundo buffer
        
         //creo una imagen del mismo ancho y alto que el 
        //lienzo
        //hacemos un casteo
        buffer2 = (BufferedImage) lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
        buffer2Graphics = buffer2.createGraphics();
        //dibujamos rectangulo blanco de tamaño del lienzo
        buffer2Graphics.setColor(Color.white);
        buffer2Graphics.fillRect(0, 0, buffer2.getWidth(), buffer2.getHeight());
    
    }
    
    
    
    
    
    @Override
    public void paint(Graphics g){
           super.paint(g);
          
        //dibujamos el buffer con las coordenadas que le indicamos
        lienzographics.drawImage(buffer, 0, 0, null);
           
           
        }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EligeColor = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        Guardar = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        lienzo = new javax.swing.JPanel();
        botonColor = new javax.swing.JButton();
        botonCirculos = new javax.swing.JButton();
        botonCuadrados = new javax.swing.JButton();
        botonTriangulo = new javax.swing.JButton();
        botonPentagono = new javax.swing.JButton();
        botonHexagono = new javax.swing.JButton();
        botonEstrella = new javax.swing.JButton();
        botonAzul = new javax.swing.JButton();
        botonAzul1 = new javax.swing.JButton();
        botonAzul2 = new javax.swing.JButton();
        botonAzul3 = new javax.swing.JButton();
        botonAzul4 = new javax.swing.JButton();
        botonAzul5 = new javax.swing.JButton();
        botonAzul6 = new javax.swing.JButton();
        botonAzul7 = new javax.swing.JButton();
        botonAzul8 = new javax.swing.JButton();
        botonAzul9 = new javax.swing.JButton();
        botonAzul10 = new javax.swing.JButton();
        botonAzul11 = new javax.swing.JButton();
        botonAzul12 = new javax.swing.JButton();
        botonAzul13 = new javax.swing.JButton();
        botonAzul14 = new javax.swing.JButton();
        botonAzul15 = new javax.swing.JButton();
        botonAzul16 = new javax.swing.JButton();
        botonAzul17 = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonLineaas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuGuardar = new javax.swing.JMenuItem();
        MenuImprimir = new javax.swing.JMenu();
        MenuEditar = new javax.swing.JMenu();

        botonAceptar.setText("Aceptar");
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAceptarMousePressed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout EligeColorLayout = new javax.swing.GroupLayout(EligeColor.getContentPane());
        EligeColor.getContentPane().setLayout(EligeColorLayout);
        EligeColorLayout.setHorizontalGroup(
            EligeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EligeColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(EligeColorLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(botonAceptar)
                .addGap(195, 195, 195)
                .addComponent(botonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EligeColorLayout.setVerticalGroup(
            EligeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EligeColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EligeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GuardarLayout = new javax.swing.GroupLayout(Guardar.getContentPane());
        Guardar.getContentPane().setLayout(GuardarLayout);
        GuardarLayout.setHorizontalGroup(
            GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
        );
        GuardarLayout.setVerticalGroup(
            GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzoMouseDragged(evt);
            }
        });
        lienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lienzoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lienzoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        botonColor.setText("Más  Colores");
        botonColor.setToolTipText("");
        botonColor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonColor.setName(""); // NOI18N
        botonColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonColorMousePressed(evt);
            }
        });

        botonCirculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/circulo.png"))); // NOI18N
        botonCirculos.setToolTipText("");
        botonCirculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCirculosMousePressed(evt);
            }
        });

        botonCuadrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuadrado.png"))); // NOI18N
        botonCuadrados.setToolTipText("");
        botonCuadrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCuadradosMousePressed(evt);
            }
        });

        botonTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/triangulo.png"))); // NOI18N
        botonTriangulo.setToolTipText("");
        botonTriangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonTrianguloMousePressed(evt);
            }
        });

        botonPentagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pentagono.png"))); // NOI18N
        botonPentagono.setToolTipText("");
        botonPentagono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPentagonoMousePressed(evt);
            }
        });

        botonHexagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hexagono.png"))); // NOI18N
        botonHexagono.setToolTipText("");
        botonHexagono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonHexagonoMousePressed(evt);
            }
        });

        botonEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estrella.png"))); // NOI18N
        botonEstrella.setToolTipText("");
        botonEstrella.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEstrellaMousePressed(evt);
            }
        });

        botonAzul.setBackground(new java.awt.Color(0, 0, 204));
        botonAzul.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzulMousePressed(evt);
            }
        });

        botonAzul1.setBackground(new java.awt.Color(0, 204, 204));
        botonAzul1.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul1MousePressed(evt);
            }
        });

        botonAzul2.setBackground(new java.awt.Color(51, 51, 255));
        botonAzul2.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul2MousePressed(evt);
            }
        });

        botonAzul3.setBackground(new java.awt.Color(102, 0, 255));
        botonAzul3.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul3MousePressed(evt);
            }
        });

        botonAzul4.setBackground(new java.awt.Color(255, 0, 102));
        botonAzul4.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul4MousePressed(evt);
            }
        });

        botonAzul5.setBackground(new java.awt.Color(204, 0, 51));
        botonAzul5.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul5MousePressed(evt);
            }
        });

        botonAzul6.setBackground(new java.awt.Color(51, 255, 51));
        botonAzul6.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul6MousePressed(evt);
            }
        });

        botonAzul7.setBackground(new java.awt.Color(51, 0, 51));
        botonAzul7.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul7MousePressed(evt);
            }
        });

        botonAzul8.setBackground(new java.awt.Color(51, 0, 51));
        botonAzul8.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul8MousePressed(evt);
            }
        });

        botonAzul9.setBackground(new java.awt.Color(153, 0, 0));
        botonAzul9.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul9MousePressed(evt);
            }
        });

        botonAzul10.setBackground(new java.awt.Color(255, 51, 51));
        botonAzul10.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul10MousePressed(evt);
            }
        });

        botonAzul11.setBackground(new java.awt.Color(0, 153, 102));
        botonAzul11.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul11MousePressed(evt);
            }
        });

        botonAzul12.setBackground(new java.awt.Color(0, 102, 102));
        botonAzul12.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul12MousePressed(evt);
            }
        });

        botonAzul13.setBackground(new java.awt.Color(255, 255, 51));
        botonAzul13.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul13MousePressed(evt);
            }
        });

        botonAzul14.setBackground(new java.awt.Color(0, 255, 255));
        botonAzul14.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul14MousePressed(evt);
            }
        });

        botonAzul15.setBackground(new java.awt.Color(0, 204, 153));
        botonAzul15.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul15MousePressed(evt);
            }
        });

        botonAzul16.setBackground(new java.awt.Color(153, 153, 153));
        botonAzul16.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul16MousePressed(evt);
            }
        });

        botonAzul17.setBackground(new java.awt.Color(0, 0, 0));
        botonAzul17.setPreferredSize(new java.awt.Dimension(80, 30));
        botonAzul17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAzul17MousePressed(evt);
            }
        });

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1487550064_draft.png"))); // NOI18N
        botonBorrar.setToolTipText("borrar");
        botonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonBorrarMousePressed(evt);
            }
        });

        botonLineaas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1487550202_translate.png"))); // NOI18N
        botonLineaas.setToolTipText("dibujar linea");
        botonLineaas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLineaasMousePressed(evt);
            }
        });

        MenuArchivo.setText("File");

        MenuGuardar.setText("Guardar...");
        MenuGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuGuardarMousePressed(evt);
            }
        });
        MenuArchivo.add(MenuGuardar);

        MenuImprimir.setText("Imprimir...");
        MenuImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuImprimirMousePressed(evt);
            }
        });
        MenuArchivo.add(MenuImprimir);

        jMenuBar1.add(MenuArchivo);

        MenuEditar.setText("Edit");
        jMenuBar1.add(MenuEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCirculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(botonHexagono, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCuadrados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(botonEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(botonPentagono, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addComponent(botonLineaas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAzul13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAzul14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAzul15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAzul16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAzul17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAzul12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonAzul7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonAzul6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonCirculos)
                                    .addComponent(botonCuadrados)
                                    .addComponent(botonTriangulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonHexagono, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEstrella)
                                    .addComponent(botonPentagono)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAzul3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAzul5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAzul4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonAzul7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonAzul13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAzul17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(botonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonLineaas)
                            .addComponent(botonBorrar))
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void lienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMousePressed
            switch (numLados) {
                case 3:
                    miforma = new Triangulo(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                
                case 4:
                    miforma = new Cuadrado(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 5:
                     miforma = new Pentagono(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 6:
                     miforma = new Hexagono(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 100:
                miforma = new Circulo(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 12:
                miforma = new Estrella(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
            }
       
//        switch(formaSeleccionada){
//        case 0: miCirculo =new Circulo(evt.getX(), evt.getY(), 10, colorSeleccionado,true);
//        miCirculo.dibujate(bufferGraphics,evt.getX());
//        break;
//        
//        case 1: miCuadrado =new Cuadrado(evt.getX(), evt.getY(), 1, colorSeleccionado,true);
//        miCuadrado.dibujate(bufferGraphics,evt.getX());
//        break;
//        
//        
//         case 2: miTriangulo =new Triangulo(evt.getX(), evt.getY(), 10, colorSeleccionado,true);
//        miCuadrado.dibujate(bufferGraphics,evt.getX());
//        break;
//        
//        
//        case 3: 
//               miPentagono = new Pentagono(evt.getX(), evt.getY(), new int[5], new int[5], colorSeleccionado, true); 
//               
//               break; 
//
//        
//        case 4: 
//  miHexagono = new Hexagono(evt.getX(), evt.getY(), new int[6], new int[6], colorSeleccionado, true); 
//               
//               break;      
//        
//        
//    }
        
        repaint(0,0,1,1);
      
    }//GEN-LAST:event_lienzoMousePressed

    
    
    
    private void lienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseDragged
        
         bufferGraphics.drawImage(buffer2, 0, 0, null);
         
         miforma.dibujate(bufferGraphics, evt.getX(),evt.getY());
         
         /*//borro lo que hubiera en el lienzo
         g2.setColor(Color.white);
         g2.fillRect(0,0,buffer.getWidth(),buffer.getHeight());
         */
          
//          bufferGraphics.drawImage(buffer2, 0, 0, null);
//          
//          switch(formaSeleccionada){
//              
//              case 0://dibujo del circulo
//      
//                    miCirculo.dibujate(bufferGraphics,evt.getX()); break;
//        
//                case 1: //dibujo del cuadrado
//                  
//                    miCuadrado.dibujate(bufferGraphics, evt.getX());
//                break;
//                
//                case 2: //dibujo del triangulo
//                  
//                    miTriangulo.dibujate(bufferGraphics, evt.getY());
//                break;
//                
//                //dibujo del pentagono
//               case 3: 
//                   miPentagono.dibujate(bufferGraphics, evt.getY());break;
//                   
//                   
//                 //dibujo del hexagono
//                 case 4: 
//                   miHexagono.dibujate(bufferGraphics, evt.getY());break;

            
//          }

     
          lienzographics.drawImage(buffer, 0, 0, null);
                   repaint(0,0,1,1);
        

    }//GEN-LAST:event_lienzoMouseDragged

    private void lienzoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseReleased
      
         miforma.dibujate(buffer2Graphics,evt.getX(),evt.getY());
        
//       switch(formaSeleccionada){
//        case 0: 
//        miCirculo.dibujate(buffer2Graphics,evt.getX());
//        break;
//        
//        case 1: 
//        miCuadrado.dibujate(buffer2Graphics,evt.getX());
//        break;
//        
//        
//        case 2: 
//        miTriangulo.dibujate(buffer2Graphics,evt.getY());
//        break;
//        
//         
//          case 3:
//              miPentagono.dibujate(buffer2Graphics, evt.getY());
//                break;
//                
//         case 4:
//              miHexagono.dibujate(buffer2Graphics, evt.getY());
//                break;
    
        
        
    }//GEN-LAST:event_lienzoMouseReleased

    private void botonColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorMousePressed
        EligeColor.setVisible(true);
    }//GEN-LAST:event_botonColorMousePressed

    private void botonAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMousePressed
        colorSeleccionado = jColorChooser1.getColor();
        EligeColor.setVisible(false);
    }//GEN-LAST:event_botonAceptarMousePressed

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
        EligeColor.setVisible(false);
    }//GEN-LAST:event_botonCancelarMousePressed

    private void botonCirculosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCirculosMousePressed
        
        
        formaSeleccionada = 0;
       numLados = 100;
    }//GEN-LAST:event_botonCirculosMousePressed

    private void botonCuadradosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCuadradosMousePressed
     
        formaSeleccionada = 1;
       numLados = 4;
    }//GEN-LAST:event_botonCuadradosMousePressed

    private void botonTrianguloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTrianguloMousePressed
      
        formaSeleccionada = 2;
         numLados = 3;
      
      
      
    }//GEN-LAST:event_botonTrianguloMousePressed

    private void botonPentagonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPentagonoMousePressed
       formaSeleccionada = 3;
       numLados = 5;
    }//GEN-LAST:event_botonPentagonoMousePressed

    private void botonHexagonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHexagonoMousePressed
        formaSeleccionada = 4;
        numLados = 6;
    }//GEN-LAST:event_botonHexagonoMousePressed

    private void botonEstrellaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstrellaMousePressed
        formaSeleccionada = 12;
        numLados = 12;
    }//GEN-LAST:event_botonEstrellaMousePressed

    
    
    private void MenuGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuGuardarMousePressed
             int seleccion = jFileChooser1.showSaveDialog(this);
      
      if (seleccion == jFileChooser1.APPROVE_OPTION){
          //el usuario a pulsado Aceptar
          File fichero = jFileChooser1.getSelectedFile();
          
          //indicamos que guarde el nombre que pongamos
          String nombre = fichero.getName();
          
          //guarda el tipo de extension,busca el punto.pasado ese punto ,
          //guarda lo que ponga
          String extension = nombre.substring(nombre.lastIndexOf('.') +1, nombre.length());
//          if (extension.equalsIgnoreCase("jpg") || extension.equalsIgnoreCase(""png)){
          
    
          try{
              ImageIO.write(buffer, extension, fichero);
          }
          catch (IOException e) {
             
          }
       }
    
      
      if(seleccion == jFileChooser1.CANCEL_OPTION){
           //el usuario a pulsado Cancelar
         
      }
                                                                                
    }//GEN-LAST:event_MenuGuardarMousePressed

    private void MenuImprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuImprimirMousePressed
       
    }//GEN-LAST:event_MenuImprimirMousePressed

    private void botonAzulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzulMousePressed
       colorSeleccionado = botonAzul.getBackground();
    }//GEN-LAST:event_botonAzulMousePressed

    private void botonAzul1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul1MousePressed
       colorSeleccionado = botonAzul1.getBackground();
    }//GEN-LAST:event_botonAzul1MousePressed

    private void botonAzul2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul2MousePressed
        colorSeleccionado = botonAzul2.getBackground();
    }//GEN-LAST:event_botonAzul2MousePressed

    private void botonAzul3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul3MousePressed
       colorSeleccionado = botonAzul3.getBackground();
    }//GEN-LAST:event_botonAzul3MousePressed

    private void botonAzul4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul4MousePressed
        colorSeleccionado = botonAzul4.getBackground();
    }//GEN-LAST:event_botonAzul4MousePressed

    private void botonAzul5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul5MousePressed
       colorSeleccionado = botonAzul5.getBackground();
    }//GEN-LAST:event_botonAzul5MousePressed

    private void botonAzul6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul6MousePressed
     colorSeleccionado = botonAzul6.getBackground();
    }//GEN-LAST:event_botonAzul6MousePressed

    private void botonAzul7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul7MousePressed
       colorSeleccionado = botonAzul7.getBackground();
    }//GEN-LAST:event_botonAzul7MousePressed

    private void botonAzul8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul8MousePressed
       colorSeleccionado = botonAzul8.getBackground();
    }//GEN-LAST:event_botonAzul8MousePressed

    private void botonAzul9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul9MousePressed
       colorSeleccionado = botonAzul9.getBackground();
    }//GEN-LAST:event_botonAzul9MousePressed

    private void botonAzul10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul10MousePressed
       colorSeleccionado = botonAzul10.getBackground();
    }//GEN-LAST:event_botonAzul10MousePressed

    private void botonAzul11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul11MousePressed
      colorSeleccionado = botonAzul11.getBackground();
    }//GEN-LAST:event_botonAzul11MousePressed

    private void botonAzul12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul12MousePressed
        colorSeleccionado = botonAzul12.getBackground();
    }//GEN-LAST:event_botonAzul12MousePressed

    private void botonAzul13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul13MousePressed
      colorSeleccionado = botonAzul13.getBackground();
    }//GEN-LAST:event_botonAzul13MousePressed

    private void botonAzul14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul14MousePressed
       colorSeleccionado = botonAzul14.getBackground();
    }//GEN-LAST:event_botonAzul14MousePressed

    private void botonAzul15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul15MousePressed
        colorSeleccionado = botonAzul15.getBackground();
    }//GEN-LAST:event_botonAzul15MousePressed

    private void botonAzul16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul16MousePressed
       colorSeleccionado = botonAzul16.getBackground();
    }//GEN-LAST:event_botonAzul16MousePressed

    private void botonAzul17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul17MousePressed
        colorSeleccionado = botonAzul17.getBackground();
    }//GEN-LAST:event_botonAzul17MousePressed

    private void botonBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMousePressed
    
    }//GEN-LAST:event_botonBorrarMousePressed

    private void botonLineaasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLineaasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLineaasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPaint1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog EligeColor;
    private javax.swing.JDialog Guardar;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenuItem MenuGuardar;
    private javax.swing.JMenu MenuImprimir;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAzul;
    private javax.swing.JButton botonAzul1;
    private javax.swing.JButton botonAzul10;
    private javax.swing.JButton botonAzul11;
    private javax.swing.JButton botonAzul12;
    private javax.swing.JButton botonAzul13;
    private javax.swing.JButton botonAzul14;
    private javax.swing.JButton botonAzul15;
    private javax.swing.JButton botonAzul16;
    private javax.swing.JButton botonAzul17;
    private javax.swing.JButton botonAzul2;
    private javax.swing.JButton botonAzul3;
    private javax.swing.JButton botonAzul4;
    private javax.swing.JButton botonAzul5;
    private javax.swing.JButton botonAzul6;
    private javax.swing.JButton botonAzul7;
    private javax.swing.JButton botonAzul8;
    private javax.swing.JButton botonAzul9;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCirculos;
    private javax.swing.JButton botonColor;
    private javax.swing.JButton botonCuadrados;
    private javax.swing.JButton botonEstrella;
    private javax.swing.JButton botonHexagono;
    private javax.swing.JButton botonLineaas;
    private javax.swing.JButton botonPentagono;
    private javax.swing.JButton botonTriangulo;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel lienzo;
    // End of variables declaration//GEN-END:variables
}
