package codigo;



import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ruben
 */
public class VentanaPaint1 extends javax.swing.JFrame {
    
    
   ImageIcon iconoTriangulo = new ImageIcon("/Imagenes/triangulo.png");
   ImageIcon iconoCirculo = new ImageIcon("/Imagenes/1487181438_triangle-up.ico");
   
    BufferedImage buffer,buffer2 = null;
 
    
    Color colorSeleccionado = Color.BLUE;
    
    int formaSeleccionada = 0;
    
    //creo un objeto de un circulo
    Circulo miCirculo;
    Cuadrado miCuadrado;
    Triangulo miTriangulo;
    Pentagono miPentagono;
    Hexagono miHexagono;
    
    //segunda forma de hacerlo
    Forma miforma;
    int numLados = 0;
    
    Graphics2D bufferGraphics,buffer2Graphics,lienzographics = null;
    
    //defino el icono
    ImageIcon icono;
    
    public VentanaPaint1() {
        initComponents();
        inicializarBuffers();
        EligeColor.setSize(630, 480);
        Guardar.setSize(750, 400);
            
           
    }
    
    
    
    private void inicializarBuffers(){
        lienzographics = (Graphics2D) lienzo.getGraphics();
        //creo una imagen del mismo ancho y alto que el 
        //lienzo
        //hacemos un casteo
        buffer = (BufferedImage) lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
         bufferGraphics = buffer.createGraphics();
        //dibujamos rectangulo blanco de tamaño del lienzo
        bufferGraphics.setColor(Color.WHITE);
        bufferGraphics.fillRect(0, 0, buffer.getWidth(), buffer.getHeight());
        
        
        
        
        
        //inicializo el segundo buffer
        
         //creo una imagen del mismo ancho y alto que el 
        //lienzo
        //hacemos un casteo
        buffer2 = (BufferedImage) lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
        buffer2Graphics = buffer2.createGraphics();
        //dibujamos rectangulo blanco de tamaño del lienzo
        buffer2Graphics.setColor(Color.white);
        buffer2Graphics.fillRect(0, 0, buffer2.getWidth(), buffer2.getHeight());
    
    }
    
    
    
    
    
    @Override
    public void paint(Graphics g){
           super.paint(g);
          
        //dibujamos el buffer con las coordenadas que le indicamos
        lienzographics.drawImage(buffer, 0, 0, null);
           
           
        }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EligeColor = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        Guardar = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        lienzo = new javax.swing.JPanel();
        botonColor = new javax.swing.JButton();
        botonCirculos = new javax.swing.JButton();
        botonCuadrados = new javax.swing.JButton();
        botonTriangulo = new javax.swing.JButton();
        botonPentagono = new javax.swing.JButton();
        botonHexagono = new javax.swing.JButton();
        botonEstrella = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        botonAceptar.setText("Aceptar");
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAceptarMousePressed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout EligeColorLayout = new javax.swing.GroupLayout(EligeColor.getContentPane());
        EligeColor.getContentPane().setLayout(EligeColorLayout);
        EligeColorLayout.setHorizontalGroup(
            EligeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EligeColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(EligeColorLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(botonAceptar)
                .addGap(195, 195, 195)
                .addComponent(botonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EligeColorLayout.setVerticalGroup(
            EligeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EligeColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EligeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GuardarLayout = new javax.swing.GroupLayout(Guardar.getContentPane());
        Guardar.getContentPane().setLayout(GuardarLayout);
        GuardarLayout.setHorizontalGroup(
            GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
        );
        GuardarLayout.setVerticalGroup(
            GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzoMouseDragged(evt);
            }
        });
        lienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lienzoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lienzoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        botonColor.setText("Color");
        botonColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonColorMousePressed(evt);
            }
        });

        botonCirculos.setText("Circulos");
        botonCirculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCirculosMousePressed(evt);
            }
        });

        botonCuadrados.setText("Cuadrados");
        botonCuadrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCuadradosMousePressed(evt);
            }
        });

        botonTriangulo.setText("Triangulo");
        botonTriangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonTrianguloMousePressed(evt);
            }
        });

        botonPentagono.setText("Pentagono");
        botonPentagono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPentagonoMousePressed(evt);
            }
        });

        botonHexagono.setText("Hexagono");
        botonHexagono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonHexagonoMousePressed(evt);
            }
        });

        botonEstrella.setText("Estrella");
        botonEstrella.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEstrellaMousePressed(evt);
            }
        });

        BotonGuardar.setText("Guardar");
        BotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonGuardarMousePressed(evt);
            }
        });

        jMenu1.setText("File");

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenu1.add(jMenu4);

        jMenu5.setText("jMenu5");
        jMenu1.add(jMenu5);

        jMenu6.setText("jMenu6");
        jMenu1.add(jMenu6);

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu7.setText("jMenu7");
        jMenu2.add(jMenu7);

        jMenu8.setText("jMenu8");
        jMenu2.add(jMenu8);

        jMenu9.setText("jMenu9");
        jMenu2.add(jMenu9);

        jMenu10.setText("jMenu10");
        jMenu2.add(jMenu10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonHexagono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCirculos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCuadrados, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonPentagono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCirculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCuadrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonPentagono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonHexagono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BotonGuardar))
                .addGap(18, 18, 18)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void lienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMousePressed
            switch (numLados) {
                case 3:
                    miforma = new Triangulo(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                
                case 4:
                    miforma = new Cuadrado(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 5:
                     miforma = new Pentagono(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 6:
                     miforma = new Hexagono(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 100:
                miforma = new Circulo(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
                case 12:
                miforma = new Estrella(evt.getX(),evt.getY(),
                colorSeleccionado,true); break;
            }
       
//        switch(formaSeleccionada){
//        case 0: miCirculo =new Circulo(evt.getX(), evt.getY(), 10, colorSeleccionado,true);
//        miCirculo.dibujate(bufferGraphics,evt.getX());
//        break;
//        
//        case 1: miCuadrado =new Cuadrado(evt.getX(), evt.getY(), 1, colorSeleccionado,true);
//        miCuadrado.dibujate(bufferGraphics,evt.getX());
//        break;
//        
//        
//         case 2: miTriangulo =new Triangulo(evt.getX(), evt.getY(), 10, colorSeleccionado,true);
//        miCuadrado.dibujate(bufferGraphics,evt.getX());
//        break;
//        
//        
//        case 3: 
//               miPentagono = new Pentagono(evt.getX(), evt.getY(), new int[5], new int[5], colorSeleccionado, true); 
//               
//               break; 
//
//        
//        case 4: 
//  miHexagono = new Hexagono(evt.getX(), evt.getY(), new int[6], new int[6], colorSeleccionado, true); 
//               
//               break;      
//        
//        
//    }
        
        repaint(0,0,1,1);
      
    }//GEN-LAST:event_lienzoMousePressed

    
    
    
    private void lienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseDragged
        
         bufferGraphics.drawImage(buffer2, 0, 0, null);
         
         miforma.dibujate(bufferGraphics, evt.getX(),evt.getY());
         
         /*//borro lo que hubiera en el lienzo
         g2.setColor(Color.white);
         g2.fillRect(0,0,buffer.getWidth(),buffer.getHeight());
         */
          
//          bufferGraphics.drawImage(buffer2, 0, 0, null);
//          
//          switch(formaSeleccionada){
//              
//              case 0://dibujo del circulo
//      
//                    miCirculo.dibujate(bufferGraphics,evt.getX()); break;
//        
//                case 1: //dibujo del cuadrado
//                  
//                    miCuadrado.dibujate(bufferGraphics, evt.getX());
//                break;
//                
//                case 2: //dibujo del triangulo
//                  
//                    miTriangulo.dibujate(bufferGraphics, evt.getY());
//                break;
//                
//                //dibujo del pentagono
//               case 3: 
//                   miPentagono.dibujate(bufferGraphics, evt.getY());break;
//                   
//                   
//                 //dibujo del hexagono
//                 case 4: 
//                   miHexagono.dibujate(bufferGraphics, evt.getY());break;

            
//          }

     
          lienzographics.drawImage(buffer, 0, 0, null);
                   repaint(0,0,1,1);
        

    }//GEN-LAST:event_lienzoMouseDragged

    private void lienzoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseReleased
      
         miforma.dibujate(buffer2Graphics,evt.getX(),evt.getY());
        
//       switch(formaSeleccionada){
//        case 0: 
//        miCirculo.dibujate(buffer2Graphics,evt.getX());
//        break;
//        
//        case 1: 
//        miCuadrado.dibujate(buffer2Graphics,evt.getX());
//        break;
//        
//        
//        case 2: 
//        miTriangulo.dibujate(buffer2Graphics,evt.getY());
//        break;
//        
//         
//          case 3:
//              miPentagono.dibujate(buffer2Graphics, evt.getY());
//                break;
//                
//         case 4:
//              miHexagono.dibujate(buffer2Graphics, evt.getY());
//                break;
    
        
        
    }//GEN-LAST:event_lienzoMouseReleased

    private void botonColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorMousePressed
        EligeColor.setVisible(true);
    }//GEN-LAST:event_botonColorMousePressed

    private void botonAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMousePressed
        colorSeleccionado = jColorChooser1.getColor();
        EligeColor.setVisible(false);
    }//GEN-LAST:event_botonAceptarMousePressed

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
        EligeColor.setVisible(false);
    }//GEN-LAST:event_botonCancelarMousePressed

    private void botonCirculosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCirculosMousePressed
        formaSeleccionada = 0;
       numLados = 100;
    }//GEN-LAST:event_botonCirculosMousePressed

    private void botonCuadradosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCuadradosMousePressed
       formaSeleccionada = 1;
       numLados = 4;
    }//GEN-LAST:event_botonCuadradosMousePressed

    private void botonTrianguloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTrianguloMousePressed
      
        formaSeleccionada = 2;
         numLados = 3;
      
      
      
    }//GEN-LAST:event_botonTrianguloMousePressed

    private void botonPentagonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPentagonoMousePressed
       formaSeleccionada = 3;
       numLados = 5;
    }//GEN-LAST:event_botonPentagonoMousePressed

    private void botonHexagonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHexagonoMousePressed
        formaSeleccionada = 4;
        numLados = 6;
    }//GEN-LAST:event_botonHexagonoMousePressed

    private void botonEstrellaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstrellaMousePressed
        formaSeleccionada = 12;
        numLados = 12;
    }//GEN-LAST:event_botonEstrellaMousePressed

    
    
    private void BotonGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMousePressed

      int seleccion = jFileChooser1.showSaveDialog(this);
      
      if (seleccion == jFileChooser1.APPROVE_OPTION){
          //el usuario a pulsado Aceptar
          File fichero = jFileChooser1.getSelectedFile();
          
          //indicamos que guarde el nombre que pongamos
          String nombre = fichero.getName();
          
          //guarda el tipo de extension,busca el punto.pasado ese punto ,
          //guarda lo que ponga
          String extension = nombre.substring(nombre.lastIndexOf('.') +1, nombre.length());
//          if (extension.equalsIgnoreCase("jpg") || extension.equalsIgnoreCase(""png)){
          
    
          try{
              ImageIO.write(buffer, extension, fichero);
          }
          catch (IOException e) {
             
          }
       }
    
      
      if(seleccion == jFileChooser1.CANCEL_OPTION){
           //el usuario a pulsado Cancelar
         
      }
    }//GEN-LAST:event_BotonGuardarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPaint1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JDialog EligeColor;
    private javax.swing.JDialog Guardar;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCirculos;
    private javax.swing.JButton botonColor;
    private javax.swing.JButton botonCuadrados;
    private javax.swing.JButton botonEstrella;
    private javax.swing.JButton botonHexagono;
    private javax.swing.JButton botonPentagono;
    private javax.swing.JButton botonTriangulo;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel lienzo;
    // End of variables declaration//GEN-END:variables
}
